  STATE_DOMESTIC_ONLY_FIELDS = []
  STATE_FOREIGN_ONLY_FIELDS  = [:country_code]
  STATE_ANYWHERE_FIELDS      = [:fullname, :address]
  STATE_ALL_FIELDS           = STATE_DOMESTIC_ONLY_FIELDS + STATE_ANYWHERE_FIELDS + STATE_FOREIGN_ONLY_FIELDS
